README.md

오늘 팀 미팅 내용을 바탕으로 Ground Rule을 작성하여 README에 작성하였습니다.

Docs: README.md에 팀원 정보 및 요구사항 기술서, Ground Rule 작성

---

BE/README.md
BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/config/JacksonConfig.java
BE/src/main/java/kr/codesquad/todo9/domain/Board.java
BE/src/main/java/kr/codesquad/todo9/domain/Card.java
BE/src/main/java/kr/codesquad/todo9/domain/Column.java
BE/src/main/java/kr/codesquad/todo9/domain/Log.java
BE/src/main/java/kr/codesquad/todo9/domain/User.java

/board 요청시 전체 board를 반환하는 API 를 생성하였습니다.
자세한 내용은 README.md 를 참조해주세요.
날짜 시간 형식이 맘에 들지 않아서 Jackson Config를 추가하였습니다.
- Close #6 Issue.

[#6] feat: Mock API 생성

---

BE/src/main/java/kr/codesquad/todo9/config/JasyptConfig.java
BE/src/main/resources/application-deploy.properties
BE/src/main/resources/application-develop.properties
BE/src/main/resources/application-local.properties

mysql 은 local에서 develop 환경으로 설정하거나, server에서 master로 배포할 경우에 사용합니다.
Close #19 Issue.

[#19] feat: mysql connection 설정 및 jasypt로 DB 접속정보 암호화

---

BE/src/main/resources/application-local.properties
BE/src/main/resources/schema.sql

Local에서 DB 변경사항이 잦을 것 같아 H2 Database를 사용하도록 설정하였습니다.
Close #20 Issue.

[#20] feat: Local 개발환경에서 사용할 H2 database 설정

---

BE/src/main/resources/schema.sql

Log의 Action이 어디서 발생했는지 알 수 있도록 수정하였습니다.(#34)
Log 테이블에 기존 정보가 담길 수 있도록 수정하였습니다.(#40)
Close #34 Issue.
Close #40 Issue.

[#34,40] refactor: Log Table 수정

---

BE/src/main/resources/schema.sql

text가 불완전하다고 하여 varchar(500)으로 지정합니다.
마찬가지로 text였던 contents를 varchar(500)으로 변경합니다.
Close #33 Issue.

[#33] refactor: User가 Profile Image Url을 담을 수 있도록 수정

---

FE/src/style/edit-note.css
FE/src/view/index.html

Card 를 더블 클릭 했을 때 Card 내용을 수정하기 위해
표시되는 Modal 팝업의 HTML, CSS 작성.

[#18] feat: Edit Note Modal HTML, CSS 작성

---

FE/src/style/edit-column.css
FE/src/view/index.html

Column Name 을 수정하기 위해 표시되는 Modal 의
HTML, CSS 작성

[#47] Column Name Edit Modal HTML, CSS 작성

---

FE/.gitignore
FE/babel.config.js
FE/package-lock.json
FE/package.json
FE/src/ts/index.ts
FE/tsconfig.json
FE/webpack.config.js

* 빌드 명령어: npx webpack
* 결과 산출 디렉토리: /FE/dist

[#46] Webpack + TypeScript + Babel 빌드 환경 파일 추가

---

FE/src/view/index.html

HTML 에서 CSS 를 포함하지 않아 잘못 나오는 문제 수정.

[#52] Edit Note (카드내용 수정) HTML, CSS Feature Fix

---

FE/src/ts/activity.ts
FE/src/ts/column.ts
FE/src/ts/common/fetchRequest.js
FE/src/ts/editcolumn.ts
FE/src/ts/editnote.ts
FE/src/ts/index.ts
FE/src/ts/lib/util.js
FE/src/ts/view.ts

* 각 화면의 기능구현을 위한 Skeleton 코드 작성.
* util js 파일 추가
* fetch js 파일 추가

[#59] feat: 기능구현을 위한 Skeleton 코드 작성

---

FE/package.json
FE/src/view/index.html
FE/webpack.config.js

* package.json: 런타임 빌드를 위한 옵션 추가.
* index.html: 빌드 된 js 파일을 참조하도록 수정.

[#55] 런타임 빌드를 위한 파일 수정

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/responseobjects/Result.java

POST 요청으로 login을 호출하면 cookie로 jwt를 저장하도록 합니다.
Close #24 Issue.

[#24] feat: login API 구현

---

FE/src/style/edit-note.css
FE/src/ts/column.ts
FE/src/ts/editcolumn.ts
FE/src/ts/editnote.ts
FE/src/ts/index.ts
FE/src/ts/modal.ts
FE/src/view/index.html
FE/webpack.config.js

- Card 더블 클릭 발생 시 Edit Note 모달 팝업 출력.
- Edit Note 모달 팝업 출력 시 Card 의 내용을 textarea 에 설정
- Edit Note 에서 textarea 의 글자가 없을 때 save button 을 비활성화
- Edit Note 에서 save 버튼 클릭 시 Card 의 content 가 수정
- Edit Note 에서 x (cancel) 버튼 클릭 시 모달이 닫힘.

[#15] 카드 내용 수정 기능 개발

---

FE/src/style/style.css
FE/src/ts/column.ts
FE/src/ts/editnote.ts
FE/src/ts/modal.ts

- query selector 를 통해여 이벤트를 등록해서
하나의 Card 에만 더블클릭 이벤트 걸렸던 문제 수정
- 바뀐 Modal 의 인터페이스 적용

[#69] fix: Edit Note 기능 버그 수정

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/api/TodoMockAPIController.java

- MockAPI와 API의 요청 경로를 서로 바꾸었습니다.
- 이제 GET /board API가 실제 Data를 반환합니다.
- Close #66 Issue.

[#66] refactor: 요청 경로 변경

---

BE/src/main/java/kr/codesquad/todo9/domain/User.java

[HotFix] fix: fix Compile Error

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/domain/Board.java

- 아직 완벽하진 않습니다. 단순히 동작만 하는 정도입니다.
- contents를 아마 요청객체를 생성해서 받아줄 것 같습니다. 이 부분은 Issue 등록할게요.
- 대략적인 요청 매커니즘이 어떻게 되는지 전달하고자 노력했습니다.
Close #25 Issue.

[#25] feat: card 생성 API 구현

---

FE/src/ts/column.ts
FE/src/ts/common/confirmMessage.js

- Card 의 x 버튼 클릭 시 사용자의 삭제 여부를 묻는 Confirm 출력.
- 사용자가 Confirm 팝업에서 '확인' 선택 시 Card 를 삭제

[#14] 카드 삭제 기능

---

BE/src/main/java/kr/codesquad/todo9/error/ErrorCode.java
BE/src/main/java/kr/codesquad/todo9/error/ErrorResponse.java
BE/src/main/java/kr/codesquad/todo9/error/GlobalRestExceptionHandler.java
BE/src/main/java/kr/codesquad/todo9/error/exception/BusinessException.java
BE/src/main/java/kr/codesquad/todo9/error/exception/EntityNotFoundException.java
BE/src/main/java/kr/codesquad/todo9/error/exception/LoginRequiredException.java
BE/src/main/java/kr/codesquad/todo9/error/exception/UserNotFoundException.java

- ErrorResponse 에러 응답 클래스를 정의하였습니다.
- ErrorCode 에러 응답에 대한 Enum을 정의하였습니다.
- Business 로직에 대한 최상위 Exception인 BusinessException을 정의하였습니다.
- Login이 되지 않은 경우 접근 할 수 없는 API를 요청한 경우 반환할 LoginRequiredException을 정의하였습니다.
- Entity를 찾지 못했을 때 발생하는 Exception의 최상위 클래스인 EntityNotFoundException을 정의하였습니다.
- EntityNotFoundException을 상속하는 User를 찾지 못했을 때 발생하는 UserNotFoundException을 정의하였습니다.
- RestController에서 발생하는 Exception을 AOP방식을 통해 ExceptionHandling하는 GlobalRestExceptionHandler 클래스를 정의하였습니다.
Close #27 Issue.

[#27] CustomException을 정의하였습니다.

---

FE/package-lock.json
FE/package.json
FE/src/ts/activity.ts
FE/src/ts/column.ts
FE/src/ts/columnTemplate.ts
FE/src/ts/common/configs.ts
FE/src/ts/index.ts
FE/src/ts/view.ts
FE/webpack.config.js

- webpack 설정 rollback
- interface 이름을 View 에서 IView 로 수정

[#89] chore: webpack 설정 rollback, interface 이름 수정

---

FE/src/ts/column.ts

- 수정된 templating 에 의한 객체 참조 코드 수정.
- 로컬 멤버 이름 수정

[#92] card 삭제 기능 버그 수정

---

FE/src/ts/column.ts

[FE] 카드 추가 미구현 부분 추가

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/domain/Board.java
BE/src/main/java/kr/codesquad/todo9/domain/Log.java

- Card를 수정하는 API를 제공합니다.
Close #28 Issue.

[#28] feat: Card 수정 API 구현

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/error/ErrorCode.java
BE/src/main/java/kr/codesquad/todo9/error/GlobalRestExceptionHandler.java
BE/src/main/java/kr/codesquad/todo9/error/exception/BoardNotFoundException.java
BE/src/main/java/kr/codesquad/todo9/error/exception/LogNotFoundException.java
BE/src/main/java/kr/codesquad/todo9/utils/JwtUtils.java

- IndexOutOfBoundsException ⇒ EntityNotFoundException으로 연결
- UserNotFoundException 적용
- BoardNotFoundException 추가 및 적용
- LoginRequiredException 적용
- LogNotFoundException 추가 및 적용
Close #97 Issue.

[#97] Custom Exception 적용

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/domain/Board.java

- addUser 경로 수정
- board API의 응답을 Log 객체로 반환하도록 수정
- card 삭제 API 구현 (삭제된 데이터는 출력되지 않습니다.)

[#29] card 삭제 API 구현

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/domain/Board.java

[Deploy] 2020-04-14 Deploy

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/api/TodoMockAPIController.java
BE/src/main/java/kr/codesquad/todo9/requestobject/ContentsObject.java
BE/src/main/java/kr/codesquad/todo9/responseobject/Result.java

- ContentsObject라는 클래스를 생성해서 요청을 받을 수 있도록 하였습니다.

[BE] Add API 요청방식 수정

---

BE/src/main/java/kr/codesquad/todo9/config/WebConfig.java

[#105] fix: Cors-Error가 DELETE에서 발생하는 이슈 수정

---

FE/src/ts/column.ts
FE/src/ts/common/configs.ts
FE/src/ts/editnote.ts
FE/src/ts/index.ts
FE/src/ts/tododatamodel.ts

- Todo 에 대한 data model 추가
- Delete, Edit 에 대한 fetch 기능 추가

[#108] 데이터 모델 추가, fetch 기능 추가

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/config/WebConfig.java
FE/src/ts/column.ts
FE/src/ts/common/configs.ts
FE/src/ts/editnote.ts
FE/src/ts/index.ts
FE/src/ts/tododatamodel.ts

[Deploy] 2020-04-13 Deploy

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java

요청 객체를 변경해달라고 하셔서 변경하였습니다!
Close #112 Issue.

[#112] refactor: Edit Card API 요청 객체 수정

---

FE/src/style/style.css
FE/src/ts/column.ts
FE/src/ts/columnTemplate.ts
FE/src/ts/index.ts
FE/src/ts/lib/util.js

-  칼럼 내 이동
-  마크업 데이터셋 추가(처음 랜더링 시)
- 데이터셋 추가 시 cardKey는 현재 추가되지 않음

[FE] 칼럼 내 이동, 마크업 데이터셋 추가

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/domain/Board.java
BE/src/main/java/kr/codesquad/todo9/requestobject/MoveCardObject.java

카드 이동기능을 구현합니다.
Close #30 Issue.

[#30] feat: 카드 이동 API 생성

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/config/WebMvcConfig.java
BE/src/main/java/kr/codesquad/todo9/interceptor/AuthInterceptor.java
BE/src/main/java/kr/codesquad/todo9/utils/JwtUtils.java

[#119] 인증 기능을 적용합니다.

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/config/WebMvcConfig.java
BE/src/main/java/kr/codesquad/todo9/requestobject/ContentsObject.java

[#31] Contents가 500자를 넘지 않도록 Validation 적용

---

FE/package-lock.json
FE/package.json
FE/src/style/login.css
FE/src/ts/column.ts
FE/src/ts/common/configs.ts
FE/src/ts/index.ts
FE/src/ts/login.ts
FE/webpack.config.js

- CORS 문제 체크하기 위해 로그인페이지만 나오는 상태에서 PR 보냅니다.

[FE] 로그인 화면 중간 PR [메인 화면 실행 안됨]

---

BE/src/main/java/kr/codesquad/todo9/interceptor/AuthInterceptor.java
BE/src/main/java/kr/codesquad/todo9/interceptor/SimpleCorsFilter.java

Cors에 대해서 좀 더 공부가 필요한 것 같습니다.
[참조](https://gist.github.com/kses1010/0a544fb0c8b4ca0b659e7d355698b060)
Close #133 Issue.

[#133] fix: cors issue 해결

---

BE/src/main/java/kr/codesquad/todo9/interceptor/AuthInterceptor.java
BE/src/main/java/kr/codesquad/todo9/interceptor/SimpleCorsFilter.java

[Deploy] 2020-04-16 Deploy

---

FE/src/style/activity.css
FE/src/ts/activity.ts
FE/src/ts/common/usercardaction.ts
FE/src/ts/index.ts

[기획서 8페이지](https://docs.google.com/presentation/d/13OX2mGk-wvwPyI06afMPITMPz9jGYLe4y2FIFBImeyA/edit#slide=id.g5d3e915f61_0_84)
- 서버로부터 최초 데이터를 받아 올 때 렌더링 되도록 기능 구현.
- 로그의 각 action 를 기반으로 활동 기록을 남길 수 있도록 기능 구현.
- show(), hide() 함수를 통해 외부에서 열고 닫을 수 있는 함수 제공.
질문사항:
1. JavaScript 나 TypeScript 에서는 activity.ts 파일에서의 templateMap 과 같은 string 을 관리하는 맵을 어떠한 형식으로 관리해야 효과적일지 궁금합니다. (파일을 따로 분리하여서?)
2. 아래와 같이 templating 이 일어나는 부분에 대한 string (ex. {userName}) 을
어떻게 관리해야 효과적일까요?
```
this.getDescriptionTemplate(UserCardAction.CREATE)
.replace("{userName}", log.user.username)
.replace("{contents}", log.afterCard.contents)
.replace("{columnName}", log.toColumn.name);
``

[#17] 활동 로그 기능 구현

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/dto/BoardDTO.java

젤로의 요청사항입니다.
Close #137 Issue.

[#137] refactor: Board 요청시 Log가 더 상세한 정보를 포함하도록 변경

---

FE/src/style/activity.css
FE/src/ts/activity.ts
FE/src/ts/column.ts
FE/src/ts/common/configs.ts
FE/src/ts/common/fetchRequest.js
FE/src/ts/editnote.ts

* Add 기능 동작 시 서버로부터 response 받은 데이터를 통해 rendering 하도록 수정.
* Add, Edit, Delete 시 서버로부터의 response 를 Activity 객체로 전달하여 출력하도록 수정.

[#141] chore: 로그 관련 동작 수정.

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
BE/src/main/java/kr/codesquad/todo9/dto/BoardDTO.java
BE/src/main/java/kr/codesquad/todo9/dto/CardDTO.java
BE/src/main/java/kr/codesquad/todo9/dto/ColumnDTO.java
BE/src/main/java/kr/codesquad/todo9/repository/CardRepository.java

이제 Card가 유저정보를 담고 있게됩니다.
@dev-angelo 
Close #146 Issue.

[#146] feature: 젤로가 요청하신 Card가 더 많은 정보를 담도록 기능 추가

---

BE/src/main/java/kr/codesquad/todo9/domain/Board.java

프론트에서 순차대로 넘겨주셔서 서버에서 역순으로 인식하도록 변경합니다.

[#150] refactor: card move 로직을 서버에서 제대로 처리하도록 수정

---

BE/src/main/java/kr/codesquad/todo9/domain/Board.java

프론트에서 순차대로 넘겨주셔서 서버에서 역순으로 인식하도록 변경합니다.

[Deploy] 2020-04-16 배포

---

BE/src/main/java/kr/codesquad/todo9/domain/Board.java
BE/src/main/resources/data.sql

[Deploy] 2020-04-16 오늘의 마지막 배포

---

FE/src/ts/column.ts
FE/src/ts/columnTemplate.ts

- Card Templating 될 때 서버로부터 전달받은 데이터를 토대도
user name 이 입력되도록 수정.

[#151] Card Templating 될 때 user name 이 입력되도록 수정

---

FE/src/ts/column.ts
FE/src/ts/editnote.ts

Delete 및 Edit 시에 대한 response 가 정상이 아닐 경우 alert 창 띄우도록 수정.

[#158] 서버로부터 받은 response 에 대한 예외처리 추가

---

BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java

BoardDTO에서 CardDTO를 반환할 때 삭제된 항목을 제거해주지 않아서 제거합니다.

[#161] fix: 삭제된 카드가 보이지 않도록 수정

---

BE/src/main/java/kr/codesquad/todo9/domain/Board.java

[#164] refactor: 프론트쪽 입력 핸들링을 하지 않도록 수정
